In [15]:
import pandas as pd

In [16]:
df = pd.read_csv(r"C:\Users\USER\Desktop\SaintsAnaconda\Flavors.csv")
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

### Groupby fn()
             multiple ways to run the group by aggregates

In [50]:
group_by_frame = df.groupby('Base Flavor')

### Fns() to use with the Group_by_frame
      different aggregates fn()
## Using sum()

In [51]:
group_by_frame.sum()

,Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Base Flavor,,,,,
Chocolate,ChocolateRocky RoadChocolte Fudge Brownie,YesYesYes,25.2,21.7,47.1
Vanilla,Mint Chocolate ChipVanillaCookie DoughPistachi...,YesNoYesNoYesNo,34.2,33.9,68.1

### Using 
    count , min , max and sum FN() 
### avec Group_by

In [47]:
df.groupby('Base Flavor').count()

             Flavor  Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate         3      3              3               3             3
Vanilla           6      6              6               6             6

In [46]:
df.groupby('Base Flavor').min()

                  Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate      Chocolate   Yes            8.2             7.0          15.2
Vanilla      Cake Batter    No            2.3             3.4           5.7

In [48]:
df.groupby('Base Flavor').max()

                 Flavor Liked  Flavor Rating  Texture Rating  Total Rating
Base Flavor
Chocolate    Rocky Road   Yes            8.8             7.6          16.6
Vanilla         Vanilla   Yes           10.0             8.0          18.0

In [49]:
df.groupby('Base Flavor').sum()

,Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Base Flavor,,,,,
Chocolate,ChocolateRocky RoadChocolte Fudge Brownie,YesYesYes,25.2,21.7,47.1
Vanilla,Mint Chocolate ChipVanillaCookie DoughPistachi...,YesNoYesNoYesNo,34.2,33.9,68.1

### Using 
       Aggregate Fn() Avec min, max ,mean, count, sum fn()
## Avec Groupby fn()

In [54]:
df.groupby('Base Flavor').agg({'Flavor Rating':['mean','sum','max','count'], 'Texture Rating':['sum','min','mean','max']})

            Flavor Rating                   Texture Rating
                     mean   sum   max count            sum  min      mean  max
Base Flavor
Chocolate             8.4  25.2   8.8     3           21.7  7.0  7.233333  7.6
Vanilla               5.7  34.2  10.0     6           33.9  3.4  5.650000  8.0

### Grouping Multiple Columns

In [63]:
df.groupby(['Base Flavor','Liked']).sum()

#OR

                                                       Flavor  Flavor Rating  \
Base Flavor Liked
Chocolate   Yes     ChocolateRocky RoadChocolte Fudge Brownie           25.2
Vanilla     No                     VanillaPistachioNeapolitan           10.8
            Yes    Mint Chocolate ChipCookie DoughCake Batter           23.4

                   Texture Rating  Total Rating
Base Flavor Liked
Chocolate   Yes              21.7          47.1
Vanilla     No               13.4          24.2
            Yes              20.5          43.9

In [64]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating':['mean','sum','max','count'], 'Texture Rating':['sum','min','mean','max']})
#or

                  Flavor Rating                   Texture Rating       \
                           mean   sum   max count            sum  min
Base Flavor Liked
Chocolate   Yes             8.4  25.2   8.8     3           21.7  7.0
Vanilla     No              3.6  10.8   4.7     3           13.4  3.4
            Yes             7.8  23.4  10.0     3           20.5  6.0


                       mean  max
Base Flavor Liked
Chocolate   Yes    7.233333  7.6
Vanilla     No     4.466667  5.0
            Yes    6.833333  8.0

### Displaying all Arithmetic Of columns in a data

In [65]:
df.groupby(['Base Flavor','Liked']).describe()

                  Flavor Rating                                             \
                          count mean       std  min   25%  50%   75%   max
Base Flavor Liked
Chocolate   Yes             3.0  8.4  0.346410  8.2  8.20  8.2  8.50   8.8
Vanilla     No              3.0  3.6  1.212436  2.3  3.05  3.8  4.25   4.7
            Yes             3.0  7.8  1.915724  6.5  6.70  6.9  8.45  10.0

                  Texture Rating            ...            Total Rating  \
                           count      mean  ...   75%  max        count
Base Flavor Liked                           ...
Chocolate   Yes              3.0  7.233333  ...  7.35  7.6          3.0
Vanilla     No               3.0  4.466667  ...  5.00  5.0          3.0
            Yes              3.0  6.833333  ...  7.25  8.0          3.0


                        mean       std   min    25%   50%    75%   max
Base Flavor Liked
Chocolate   Yes    15.700000  0.781025  15.2  15.25  15.3  15.95  16.6
Vanilla     No      8.066667  2.098412   5.7   7.25   8.8   9.25   9.7
            Yes    14.633333  2.950141  12.5  12.95  13.4  15.70  18.0

[3 rows x 24 columns]