## Filtering And Ordering

In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r"C:\Users\USER\Desktop\SaintsAnaconda\world_population.csv")

In [3]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

### Filtering by coumns

In [4]:
df[df['Rank'] <= 10]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24

### Filtering by Specifying Columns

In [5]:
specific_countries = ['Brazil','Indonesia','Nigeria','Russia']

df[df['Country'].isin(specific_countries)]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
27,7,BRA,Brazil,Brasilia,South America,215313498.0,213196304.0,205188205.0,196353492.0,175873720.0,150706446.0,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
93,4,IDN,Indonesia,Jakarta,Asia,275501339.0,271857970.0,259091970.0,244016173.0,214072421.0,182159874.0,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
149,6,NGA,Nigeria,Abuja,Africa,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
171,9,RUS,Russia,Moscow,Europe,144713314.0,145617329.0,144668389.0,143242599.0,146844839.0,148005704.0,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81

### Filtering By String Value

In [6]:
df[df['Country'].str.contains('United')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
220,21,GBR,United Kingdom,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
221,3,USA,United States,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
222,200,VIR,United States Virgin Islands,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [7]:
#Or 
df[df['Continent'].str.contains('Asia')]  #brings_All_countries in asia contained in the file

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,4.112877e+07,3.897223e+07,3.375350e+07,2.818967e+07,1.954298e+07,1.069480e+07,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
9,140,ARM,Armenia,Yerevan,Asia,2.780469e+06,2.805608e+06,2.878595e+06,2.946293e+06,3.168523e+06,3.556539e+06,3135123.0,2534377.0,29743.0,93.4831,0.9962,0.03
13,91,AZE,Azerbaijan,Baku,Asia,1.035807e+07,NaN,9.863480e+06,9.237202e+06,8.190337e+06,7.427836e+06,6383060.0,5425317.0,86600.0,119.6082,1.0044,0.13
15,154,BHR,Bahrain,Manama,Asia,1.472233e+06,1.477469e+06,1.362142e+06,1.213645e+06,7.114420e+05,5.174180e+05,362595.0,222555.0,765.0,1924.4876,1.0061,0.02
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
23,165,BTN,Bhutan,Thimphu,Asia,7.824550e+05,7.725060e+05,7.432740e+05,7.055160e+05,5.872070e+05,5.584420e+05,415257.0,298894.0,38394.0,20.3796,1.0064,0.01
29,175,BRN,Brunei,Bandar Seri Begawan,Asia,4.490020e+05,4.417250e+05,4.214370e+05,3.960530e+05,3.339260e+05,2.619280e+05,187921.0,133343.0,5765.0,77.8841,1.0081,0.01
33,73,KHM,Cambodia,Phnom Penh,Asia,1.676784e+07,1.639686e+07,1.541752e+07,1.436353e+07,1.211884e+07,8.910808e+06,6198959.0,6708525.0,181035.0,92.6221,1.0108,0.21
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
73,131,GEO,Georgia,Tbilisi,Asia,3.744385e+06,3.765912e+06,3.771132e+06,NaN,NaN,NaN,NaN,NaN,69700.0,53.7214,0.9964,0.05
89,104,HKG,Hong Kong,Hong Kong,Asia,7.488865e+06,7.500958e+06,7.399838e+06,7.132438e+06,6.731195e+06,5.838574e+06,4978544.0,3955072.0,1104.0,6783.3922,0.9992,0.09
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
94,17,IRN,Iran,Tehran,Asia,8.855057e+07,8.729019e+07,8.179084e+07,7.537386e+07,6.554438e+07,5.579363e+07,38520664.0,28449705.0,1648195.0,53.7258,1.0071,1.11
95,35,IRQ,Iraq,Baghdad,Asia,4.449612e+07,4.255698e+07,3.775781e+07,3.126488e+07,2.462886e+07,1.765838e+07,13653369.0,9811347.0,438317.0,101.5158,1.0221,0.56
98,98,ISR,Israel,Jerusalem,Asia,9.038309e+06,8.757489e+06,8.007778e+06,7.328445e+06,6.116958e+06,4.803254e+06,3744608.0,2907307.0,20770.0,435.1617,1.0155,0.11
102,11,JPN,Japan,Tokyo,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
104,83,JOR,Jordan,Amman,Asia,1.128587e+07,1.092872e+07,9.494246e+06,6.931258e+06,5.056174e+06,3.480587e+06,2216903.0,1557374.0,89342.0,126.3221,1.0123,0.14
105,66,KAZ,Kazakhstan,Nursultan,Asia,1.939800e+07,1.897924e+07,1.783591e+07,1.662784e+07,1.523625e+07,1.686656e+07,14172710.0,12265305.0,2724900.0,7.1188,1.0105,0.24
108,129,KWT,Kuwait,Kuwait City,Asia,4.268873e+06,4.360444e+06,3.908743e+06,2.943356e+06,1.934901e+06,1.674938e+06,1493870.0,802786.0,17818.0,239.5821,1.0044,0.05
109,110,KGZ,Kyrgyzstan,Bishkek,Asia,6.630623e+06,6.424874e+06,5.914980e+06,5.483774e+06,4.935182e+06,4.394734e+06,3691209.0,3016384.0,199951.0,33.1612,1.0158,0.08
110,103,LAO,Laos,Vientiane,Asia,7.529475e+06,7.319399e+06,6.787419e+06,6.323418e+06,5.430853e+06,4.314443e+06,3297519.0,2675283.0,236800.0,31.7968,1.0141,0.09
112,119,LBN,Lebanon,Beirut,Asia,5.489739e+06,5.662923e+06,6.398940e+06,4.995800e+06,4.320642e+06,3.593700e+06,2963702.0,2381791.0,10452.0,525.2334,0.9816,0.07
119,167,MAC,Macau,Concelho de Macau,Asia,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
122,45,MYS,Malaysia,Kuala Lumpur,Asia,3.393822e+07,3.319999e+07,3.106883e+07,NaN,NaN,1.751705e+07,13215707.0,10306508.0,330803.0,102.5934,1.0109,0.43
123,174,MDV,Maldives,Malé,Asia,5.237870e+05,5.144380e+05,4.355820e+05,NaN,NaN,2.249570e+05,164887.0,123243.0,300.0,1745.9567,1.0045,0.01
135,134,MNG,Mongolia,Ulaanbaatar,Asia,3.398366e+06,3.294335e+06,2.964749e+06,2.702520e+06,2.450979e+06,2.161433e+06,1697780.0,1293880.0,1564110.0,2.1727,1.0151,0.04
140,26,MMR,Myanmar,Nay Pyi Taw,Asia,5.417931e+07,5.342320e+07,5.148395e+07,4.939099e+07,4.553833e+07,4.009955e+07,33465781.0,27284112.0,676578.0,80.0784,1.0071,0.68
143,49,NPL,Nepal,Kathmandu,Asia,3.054758e+07,2.934863e+07,2.761032e+07,2.716157e+07,2.455950e+07,1.961653e+07,15600442.0,12501285.0,147181.0,207.5511,1.0171,0.38
151,56,PRK,North Korea,Pyongyang,Asia,2.606942e+07,2.586747e+07,2.525802e+07,2.468644e+07,2.336706e+07,2.079952e+07,17973650.0,14996879.0,120538.0,216.2755,1.0038,0.33
155,127,OMN,Oman,Muscat,Asia,4.576298e+06,4.543399e+06,4.191776e+06,2.881914e+06,2.344253e+06,1.804524e+06,1017462.0,670693.0,309500.0,14.7861,1.0123,0.06
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
158,122,PSE,Palestine,Ramallah,Asia,5.250072e+06,5.019401e+06,4.484614e+06,3.992278e+06,3.139954e+06,2.124609e+06,1453620.0,1118241.0,6220.0,844.0630,1.0227,0.07
163,13,PHL,Philippines,Manila,Asia,1.155590e+08,1.121910e+08,1.030314e+08,9.463670e+07,7.795822e+07,6.155890e+07,48419546.0,37435586.0,342353.0,337.5434,1.0147,1.45
167,143,QAT,Qatar,Doha,Asia,2.695122e+06,2.760385e+06,2.414573e+06,1.713504e+06,6.459370e+05,4.416750e+05,277450.0,118007.0,11586.0,232.6189,1.0026,0.03
182,41,SAU,Saudi Arabia,Riyadh,Asia,3.640882e+07,3.599711e+07,3.274985e+07,2.941193e+07,2.154739e+07,1.600476e+07,10171710.0,6106191.0,2149690.0,16.9368,1.0128,0.46
187,113,SGP,Singapore,Singapore,Asia,5.975689e+06,5.909869e+06,5.650018e+06,5.163590e+06,4.053602e+06,3.022209e+06,2400729.0,2061831.0,710.0,8416.4634,1.0058,0.07
194,29,KOR,South Korea,Seoul,Asia,5.181581e+07,5.184469e+07,5.099440e+07,4.881304e+07,4.678859e+07,4.412004e+07,38170501.0,32601143.0,100210.0,517.0722,0.9997,0.65
197,61,LKA,Sri Lanka,Colombo,Asia,2.183214e+07,2.171508e+07,2.133670e+07,2.066856e+07,1.877637e+07,1.720409e+07,14943645.0,12388769.0,65610.0,332.7563,1.0027,0.27
202,60,SYR,Syria,Damascus,Asia,2.212525e+07,2.077260e+07,1.920518e+07,2.233756e+07,1.630765e+07,1.240900e+07,8898954.0,6319199.0,185180.0,119.4797,1.0376,0.28
203,57,TWN,Taiwan,Taipei,Asia,2.389339e+07,2.382146e+07,2.351214e+07,2.308308e+07,2.219473e+07,2.058617e+07,18100281.0,14957870.0,36193.0,660.1662,1.0014,0.30
204,95,TJK,Tajikistan,Dushanbe,Asia,9.952787e+06,9.543207e+06,8.524063e+06,7.621779e+06,6.272998e+06,5.417860e+06,4045965.0,2993019.0,143100.0,69.5513,1.0208,0.12
206,20,THA,Thailand,Bangkok,Asia,7.169703e+07,7.147566e+07,7.029440e+07,6.827049e+07,6.306660e+07,5.522841e+07,45737753.0,NaN,513120.0,139.7276,1.0013,0.90
207,155,TLS,Timor-Leste,Dili,Asia,NaN,1.299995e+06,1.205813e+06,1.088486e+06,NaN,7.581060e+05,642224.0,554021.0,14874.0,90.1772,1.0154,0.02
213,18,TUR,Turkey,Ankara,Asia,8.534124e+07,8.413543e+07,7.964618e+07,7.319534e+07,6.411355e+07,5.432414e+07,44089069.0,35540990.0,783562.0,108.9145,1.0067,1.07
214,111,TKM,Turkmenistan,Ashgabat,Asia,6.430770e+06,6.250438e+06,5.766431e+06,5.267970e+06,4.569132e+06,3.720278e+06,2862903.0,2201432.0,488100.0,13.1751,1.0140,0.08
219,97,ARE,United Arab Emirates,Abu Dhabi,Asia,9.441129e+06,9.287289e+06,8.916899e+06,8.481771e+06,3.275333e+06,1.900151e+06,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
224,43,UZB,Uzbekistan,Tashkent,Asia,3.462765e+07,3.352666e+07,3.094942e+07,2.861423e+07,2.492555e+07,2.057910e+07,15947129.0,12011361.0,447400.0,77.3975,1.0160,0.43
228,16,VNM,Vietnam,Hanoi,Asia,9.818686e+07,9.664868e+07,9.219140e+07,8.741101e+07,7.900114e+07,6.691261e+07,52968270.0,41928849.0,331212.0,296.4472,1.0074,1.23
231,46,YEM,Yemen,Sanaa,Asia,3.369661e+07,3.228405e+07,2.851654e+07,2.474395e+07,1.862870e+07,1.337512e+07,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42

### Setting Our Own INdex

In [8]:
df2 = df.set_index('Country')  #or   #df2 = df.set_index('Continent')

df2

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

### Filtering WHat Columns To keep

## Arguments to use in a Filter fn()

In [9]:
df2.filter(items = ['Continent','CCA3','2020 Population'])

                  Continent CCA3  2020 Population
Country
Afghanistan            Asia  AFG       38972230.0
Albania              Europe  ALB        2866849.0
Algeria              Africa  DZA       43451666.0
American Samoa      Oceania  ASM          46189.0
Andorra              Europe  AND          77700.0
...                     ...  ...              ...
Wallis and Futuna   Oceania  WLF          11655.0
Western Sahara       Africa  ESH         556048.0
Yemen                  Asia  YEM       32284046.0
Zambia               Africa  ZMB       18927715.0
Zimbabwe             Africa  ZWE       15669666.0

[234 rows x 3 columns]

### Specifying Our Own axis

In [15]:
# df2.filter(items = ['Continent','CCA3','2020 Population'],axis = 1)
#or 
df2.filter(items = ['Zimbabwe','Nigeria'],axis = 0 )

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20
Nigeria,6,NGA,Abuja,Africa,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74

In [21]:
df2.filter(like = 'Republic' , axis = 0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Central African Republic,117,CAF,Bangui,Africa,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
Czech Republic,88,CZE,Prague,Europe,10493986.0,10530953.0,10523798.0,10464749.0,10234710.0,10301192.0,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13
Dominican Republic,84,DOM,Santo Domingo,North America,11228821.0,10999664.0,10405832.0,9775755.0,8540791.0,7129004.0,5755800.0,4475871.0,48671.0,230.7087,1.0100,0.14
Republic of the Congo,114,COG,Brazzaville,Africa,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07

### Searching specific Data In yOUr Index

In [22]:
#or

df2.loc['United States']

Rank                                          3
CCA3                                        USA
Capital                        Washington, D.C.
Continent                         North America
2022 Population                     338289857.0
2020 Population                     335942003.0
2015 Population                     324607776.0
2010 Population                     311182845.0
2000 Population                     282398554.0
1990 Population                     248083732.0
1980 Population                     223140018.0
1970 Population                     200328340.0
Area (km²)                            9372610.0
Density (per km²)                       36.0935
Growth Rate                              1.0038
World Population Percentage                4.24
Name: United States, dtype: object

In [23]:
#or

df.iloc[6]

Rank                                     224
CCA3                                     AIA
Country                             Anguilla
Capital                           The Valley
Continent                      North America
2022 Population                      15857.0
2020 Population                      15585.0
2015 Population                      14525.0
2010 Population                      13172.0
2000 Population                      11047.0
1990 Population                       8316.0
1980 Population                       6560.0
1970 Population                       6283.0
Area (km²)                              91.0
Density (per km²)                   174.2527
Growth Rate                           1.0066
World Population Percentage              0.0
Name: 6, dtype: object

### Ordering

In [24]:
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [26]:
# df[df['Rank'] < 12].sort_values(by = 'Rank')

#or 

df[df['Rank'] < 12].sort_values(by = 'Rank',ascending = False )  #For Descending Order

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
102,11,JPN,Japan,Tokyo,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88

### Nested Ordering

In [29]:
df[df['Rank'] < 12].sort_values(by = ['Country','Rank'], ascending = [False,False])

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
131,10,MEX,Mexico,Mexico City,North America,1.275041e+08,1.259983e+08,1.201499e+08,1.125324e+08,9.787344e+07,8.172043e+07,67705186.0,50289306.0,1964375.0,64.9082,1.0063,1.60
102,11,JPN,Japan,Tokyo,Asia,1.239517e+08,1.252448e+08,1.272509e+08,1.281054e+08,1.268039e+08,1.236863e+08,117624196.0,105416839.0,377930.0,327.9753,0.9947,1.55
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15