In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv(r"C:\Users\USER\Desktop\SaintsAnaconda\LOTR.csv")
df1

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks

In [4]:
df2 = pd.read_csv(r"C:\Users\USER\Desktop\SaintsAnaconda\LOTR 2.csv")
df2

   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

### Merge fn()
   joins two data frames like the joins.
### Default : natural joins

### like Using
  .merge(df2, how = 'inner')

In [6]:
df1.merge(df2, how = 'inner')

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

### Fact checking if it truly displays default
   .merge(df2, how = 'inner' , on = 'specify user column')

In [7]:
#df1.merge(df2, how = 'inner', on = 'FellowshipID')
#Or  
df1.merge(df2, how = 'inner', on = ['FellowshipID','FirstName'])

   FellowshipID FirstName     Skills  Age
0          1001     Frodo     Hiding   50
1          1002   Samwise  Gardening   39

### Using
  .merge(df, how = 'outer')
### Defaults : full outer join; Data that both DF have in them
### Note: 
   NaN means: Not a nUMBER; when a common match can't be found in both df's data

In [8]:
df1.merge(df2, how = 'outer')

   FellowshipID FirstName     Skills     Age
0          1001     Frodo     Hiding    50.0
1          1002   Samwise  Gardening    39.0
2          1003   Gandalf     Spells     NaN
3          1004    Pippin  Fireworks     NaN
4          1006   Legolas        NaN  2931.0
5          1007    Elrond        NaN  6520.0
6          1008  Barromir        NaN    51.0

### how = 'Left'  (left outer join)
    all data from the left df , then brings in matching data from the other df

In [9]:
df1.merge(df2, how = 'left')

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding  50.0
1          1002   Samwise  Gardening  39.0
2          1003   Gandalf     Spells   NaN
3          1004    Pippin  Fireworks   NaN

### how = 'right'
    exact opposite of the how = 'left' ,
    all data from the right table then matching from the left

In [10]:
df1.merge(df2, how = 'right')

   FellowshipID FirstName     Skills   Age
0          1001     Frodo     Hiding    50
1          1002   Samwise  Gardening    39
2          1006   Legolas        NaN  2931
3          1007    Elrond        NaN  6520
4          1008  Barromir        NaN    51

### how = 'cross'  : Cross Join
    takes each value in the left df and compares with all the value on the right df
    and repeats it for the next value

In [11]:
df1.merge(df2, how = 'cross')

    FellowshipID_x FirstName_x     Skills  FellowshipID_y FirstName_y   Age
0             1001       Frodo     Hiding            1001       Frodo    50
1             1001       Frodo     Hiding            1002     Samwise    39
2             1001       Frodo     Hiding            1006     Legolas  2931
3             1001       Frodo     Hiding            1007      Elrond  6520
4             1001       Frodo     Hiding            1008    Barromir    51
5             1002     Samwise  Gardening            1001       Frodo    50
6             1002     Samwise  Gardening            1002     Samwise    39
7             1002     Samwise  Gardening            1006     Legolas  2931
8             1002     Samwise  Gardening            1007      Elrond  6520
9             1002     Samwise  Gardening            1008    Barromir    51
10            1003     Gandalf     Spells            1001       Frodo    50
11            1003     Gandalf     Spells            1002     Samwise    39
12            1003     Gandalf     Spells            1006     Legolas  2931
13            1003     Gandalf     Spells            1007      Elrond  6520
14            1003     Gandalf     Spells            1008    Barromir    51
15            1004      Pippin  Fireworks            1001       Frodo    50
16            1004      Pippin  Fireworks            1002     Samwise    39
17            1004      Pippin  Fireworks            1006     Legolas  2931
18            1004      Pippin  Fireworks            1007      Elrond  6520
19            1004      Pippin  Fireworks            1008    Barromir    51

### Using Joins

In [17]:
df1.join(df2, on = 'FellowshipID', how = 'outer', lsuffix = '_Left', rsuffix = '_Right')

#OR

,FellowshipID,FellowshipID_Left,FirstName_Left,Skills,FellowshipID_Right,FirstName_Right,Age
NaN,0,NaN,NaN,NaN,1001.0,Frodo,50.0
NaN,1,NaN,NaN,NaN,1002.0,Samwise,39.0
NaN,2,NaN,NaN,NaN,1006.0,Legolas,2931.0
NaN,3,NaN,NaN,NaN,1007.0,Elrond,6520.0
NaN,4,NaN,NaN,NaN,1008.0,Barromir,51.0
0.0,1001,1001.0,Frodo,Hiding,NaN,NaN,NaN
1.0,1002,1002.0,Samwise,Gardening,NaN,NaN,NaN
2.0,1003,1003.0,Gandalf,Spells,NaN,NaN,NaN
3.0,1004,1004.0,Pippin,Fireworks,NaN,NaN,NaN

### To make join work as merge
  Calling it in another df

In [20]:
df5 = df1.set_index('FellowshipID').join(df2.set_index('FellowshipID'), 
                                         lsuffix = '_Left', rsuffix = '_Right',how = 'outer')
df5

             FirstName_Left     Skills FirstName_Right     Age
FellowshipID
1001                  Frodo     Hiding           Frodo    50.0
1002                Samwise  Gardening         Samwise    39.0
1003                Gandalf     Spells             NaN     NaN
1004                 Pippin  Fireworks             NaN     NaN
1006                    NaN        NaN         Legolas  2931.0
1007                    NaN        NaN          Elrond  6520.0
1008                    NaN        NaN        Barromir    51.0

### Concatenate
    this puts a df on top of each other, 
         instead of beside one another like the merge and join

In [22]:
#pd.concat([df1,df2])
#OR
pd.concat([df1,df2],join = 'inner')  #OR join = 'outer'

   FellowshipID FirstName
0          1001     Frodo
1          1002   Samwise
2          1003   Gandalf
3          1004    Pippin
0          1001     Frodo
1          1002   Samwise
2          1006   Legolas
3          1007    Elrond
4          1008  Barromir

### Concat by Axis
   """Axis = 1 ; column based concat
      Axis = 0 ; index/row based concat
   """

In [25]:
pd.concat([df1,df2],join = 'outer',axis = 1)

   FellowshipID FirstName     Skills  FellowshipID FirstName   Age
0        1001.0     Frodo     Hiding          1001     Frodo    50
1        1002.0   Samwise  Gardening          1002   Samwise    39
2        1003.0   Gandalf     Spells          1006   Legolas  2931
3        1004.0    Pippin  Fireworks          1007    Elrond  6520
4           NaN       NaN        NaN          1008  Barromir    51

### Append
   """appending rows to the end of one df 
   to another df and return that df"""

## df1.append(df2) 
    """Already removed from new version of pandas"""